version: '3'
services:
  codeworks-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeworks-db
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data
  codeworks-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=cw-messages
    ports:
      - 27017:27017
    volumes:
      - .mongodata:/data/db
